# this is a makefile
main.out:bubble.o insertion.o shell.o recursion.o  QuickSort.o main.c
	gcc -g bubble.o insertion.o shell.o recursion.o QuickSort.o main.c -o main.out
bubble.o:bubble.c
	gcc -c -g bubble.c -o bubble.o
insertion.o:insertion.c
	gcc -c -g insertion.c -o insertion.o
shell.o:shell.c
	gcc -c -g shell.c -o shell.o
recursion.o:recursion.c
	gcc -c -g recursion.c -o recursion.o
QuickSort.o:QuickSort.c
	gcc -c -g QuickSort.c -o QuickSort.o
